version: '3.1'

services:
    postgres:   
        image: postgres 
        ports:
            - 5438:5432
        env_file: ../.env
        volumes:
            - ../pgdb/:/var/lib/postgresql/data

    redis:
        image: redis
        ports:
            - '127.0.0.1:6379:6379'
        restart: always
        
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080