# Generated by Django 2.2.24 on 2021-10-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_family', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=188)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('os_family', models.CharField(blank=True, max_length=255, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_adress', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'UserInfo',
                'verbose_name_plural': 'UserInfos',
            },
        ),
    ]
