# Generated by Django 2.2.24 on 2021-10-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False, 'verbose_name': 'UserInfo', 'verbose_name_plural': 'UserInfos'},
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table=None,
        ),
    ]
