# Generated by Django 2.2.24 on 2021-10-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211016_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_id',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='admin', max_length=188),
            preserve_default=False,
        ),
    ]
