# Generated by Django 2.2.24 on 2021-10-16 01:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211016_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 16, 1, 20, 58, 23087, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
