# Generated by Django 3.2.8 on 2021-10-07 18:06

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_status_expired',
            field=models.DateTimeField(blank=True, default=files.models.after_seven_day, null=True, verbose_name='Bitmə vaxtı'),
        ),
    ]
