# Generated by Django 3.2.8 on 2021-10-07 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_file_is_status_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='view_user',
            field=models.ManyToManyField(related_name='files_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
