# Generated by Django 3.2.8 on 2021-10-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_view_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.SlugField(default='asdad', max_length=500),
            preserve_default=False,
        ),
    ]
