# Generated by Django 3.2.8 on 2021-10-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(default='', max_length=500),
        ),
    ]
