# Generated by Django 3.2.8 on 2021-10-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_file_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
