# Generated by Django 3.2.8 on 2021-10-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20211008_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='email',
        ),
    ]
