# Generated by Django 3.2.8 on 2021-10-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_remove_file_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='username',
        ),
    ]
