# Generated by Django 3.2.8 on 2021-10-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_remove_file_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='access',
            field=models.IntegerField(blank=True, choices=[(1, 'SHOW'), (2, 'COMMIT AND SHOW')], null=True),
        ),
    ]
