# Generated by Django 3.2.8 on 2021-10-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_file_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='access',
            new_name='access_type',
        ),
    ]
