# Generated by Django 3.2.8 on 2021-10-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_rename_access_file_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='access_type',
            field=models.IntegerField(choices=[(0, 'NO ACCESS'), (1, 'SHOW'), (2, 'COMMIT AND SHOW')], default=0),
        ),
    ]
