# Generated by Django 3.2.8 on 2021-10-08 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0011_alter_file_access_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='view_user',
        ),
        migrations.CreateModel(
            name='AccessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.IntegerField(choices=[(0, 'NO ACCESS'), (1, 'SHOW'), (2, 'COMMIT AND SHOW')], default=0)),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.file')),
                ('views_user', models.ManyToManyField(related_name='access_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acces user',
                'verbose_name_plural': 'Acess users',
            },
        ),
    ]
