# Generated by Django 3.2.8 on 2021-10-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20211008_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessuser',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_access', to='files.file'),
        ),
    ]
