# Generated by Django 3.2.8 on 2021-10-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_accessuser_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessuser',
            name='files',
        ),
        migrations.AddField(
            model_name='accessuser',
            name='files',
            field=models.ManyToManyField(related_name='file_access', to='files.File'),
        ),
    ]
