# Generated by Django 3.2.8 on 2021-10-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='users',
        ),
    ]
