# Generated by Django 3.2.8 on 2021-10-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0018_auto_20211009_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
