# Generated by Django 2.2.24 on 2021-10-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_remove_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
