# Generated by Django 2.2.24 on 2021-10-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_auto_20211012_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=500),
        ),
    ]
